#define DS_CENTER             0x0800L
#define DS_CENTER             0x0800L
#define WS_MINIMIZEBOX        0x00020000L
#define WS_SYSMENU            0x00080000L
#define WS_VISIBLE            0x10000000L
#define WS_OVERLAPPED         0x00000000L
#define DS_MODALFRAME         0x80L
#define DS_3DLOOK             0x0004L
#define WS_CAPTION            0xC00000L
#define WS_CHILD              0x40000000
#define ES_AUTOHSCROLL        0x80L
#define ES_LEFT               0
#define WS_MAXIMIZEBOX        0x10000L
#define WS_MENUITEM           0x80000000L
#define ES_MULTILINE          0x4L
#define WS_VSCROLL            0x200000L
#define ES_AUTOHSCROLL        0x80L
#define WS_POPUP              0x80000000L
#define IDOK                  1
#define WS_GROUP              0x20000L
#define SS_BLACKFRAME         0x7L
#define SS_CENTER             0x1L
#define SS_ICON               0x3L
#define BS_AUTORADIOBUTTON    0x9L
#define BS_AUTORADIOBUTTON    0x9L
#define BS_3STATE             0x5L
#define BS_AUTO3STATE         0x6L
#define BS_AUTOCHECKBOX       0x3L
#define BS_AUTORADIOBUTTON    0x9L
#define BS_CHECKBOX           0x2L
#define BS_DEFPUSHBUTTON      0x1L
#define BS_DIBPATTERN         5
#define BS_DIBPATTERN8X8      8
#define BS_DIBPATTERNPT       6
#define BS_GROUPBOX           0x7L
#define BS_HATCHED            2
#define BS_HOLLOW             BS_NULL
#define BS_INDEXED            4
#define BS_LEFTTEXT           0x20L
#define BS_NULL               1
#define BS_OWNERDRAW          0xBL
#define BS_PATTERN            3
#define BS_PATTERN8X8         7
#define BS_PUSHBUTTON         0x0L
#define BS_RADIOBUTTON        0x4L
#define BS_SOLID              0
#define BS_USERBUTTON         0x8L
#define SS_BLACKFRAME         0x7L
#define SS_BLACKRECT          0x4L
#define SS_CENTER             0x1L
#define SS_GRAYFRAME          0x8L
#define SS_GRAYRECT           0x5L
#define SS_ICON               0x3L
#define SS_LEFT               0x0L
#define SS_LEFTNOWORDWRAP     0xCL
#define SS_RIGHT              0x2L
#define SS_SIMPLE             0xBL
#define SS_USERITEM           0xAL
#define SS_WHITEFRAME         0x9L
#define SS_WHITERECT          0x6L
#define SS_OWNERDRAW 		0x0DL
#define SS_BITMAP 		0x0EL
#define SS_ENHMETAFILE 		0x0FL
#define SS_ETCHEDHORZ 		0x10L
#define SS_ETCHEDVERT 		0x11L
#define SS_ETCHEDFRAME 		0x12L
#define SS_TYPEMASK 		0x1FL
#define SS_NOPREFIX 		0x80L
#define SS_NOTIFY 		0x100L
#define SS_CENTERIMAGE 		0x200L
#define SS_RIGHTJUST 		0x400L
#define SS_REALSIZEIMAGE 	0x800L
#define SS_SUNKEN 		0x1000L
#define SS_ENDELLIPSIS 		0x4000L
#define SS_PATHELLIPSIS 	0x8000L
#define SS_WORDELLIPSIS 	0x0C000L
#define SS_ELLIPSISMASK 	0x0C000L

#define WS_TABSTOP            0x10000L







