  ; ===========================================
  ; d3dim.inc copyright MASM32 1998 - 2003
  ; ===========================================

Direct3DCreate PROTO :DWORD,:DWORD,:DWORD
Direct3D_HALCleanUp PROTO :DWORD,:DWORD
FlushD3DDevices2 PROTO :DWORD
FlushD3DDevices PROTO :DWORD
PaletteAssociateNotify PROTO :DWORD,:DWORD,:DWORD,:DWORD
PaletteUpdateNotify PROTO :DWORD,:DWORD,:DWORD,:DWORD,:DWORD
SurfaceFlipNotify PROTO :DWORD
