  ; ===========================================
  ; iprop.inc copyright MASM32 1998 - 2003
  ; ===========================================

FmtIdToPropStgName PROTO :DWORD,:DWORD
FreePropVariantArray PROTO :DWORD,:DWORD
PropStgNameToFmtId PROTO :DWORD,:DWORD
PropVariantClear PROTO :DWORD
PropVariantCopy PROTO :DWORD,:DWORD
StgCreatePropSetStg PROTO :DWORD,:DWORD,:DWORD
StgCreatePropStg PROTO :DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD
StgOpenPropStg PROTO :DWORD,:DWORD,:DWORD,:DWORD,:DWORD
